name: Publish playlists

on:
  schedule:
    - cron:  '30 1 * * *'
  watch:
    types: started

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: npm install

    - name: Generate Playlists
      run: |
        npm run generate https://iptv-org.github.io/iptv/languages/cmn.m3u cmn.txt
        npm run generate https://iptv-org.github.io/iptv/languages/zho.m3u zho.txt
        npm run generate https://iptv-org.github.io/iptv/languages/jpn.m3u jpn.txt
        npm run generate https://iptv-org.github.io/iptv/languages/kor.m3u kor.txt

    - name: Clean
      run: rm -rf .github

    - name: Git init
      run: |
        git config --global user.name "Actions"
        git config --global user.email "actions@github.com"
 
    - name: Commit
      run: git add --all && git commit -m 'Deploy pages'

    - name: Push to GitHub Pages
      run: git checkout -b gh-pages && git push -f origin gh-pages
